on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created:  ${{ steps.release.outputs.release_created }}
      release_tag:  ${{ steps.release.outputs.tag_name }}
      major:  ${{ steps.release.outputs.major }}
      minor:  ${{ steps.release.outputs.minor }}
      patch:  ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node

  okay-release-windows:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build
        uses: borales/actions-yarn@v4
        with:
          cmd: build:win
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.release_tag }} ./dist/mterm-${{ needs.release-please.outputs.major}}.${{ needs.release-please.outputs.minor}}.${{ needs.release-please.outputs.patch}}${{ vars.RELEASE_LABEL }}-setup.exe

  okay-release-linux:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build
        uses: borales/actions-yarn@v4
        with:
          cmd: build:linux
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        # mterm_1.0.6-beta_amd64.deb
        run: gh release upload ${{ needs.release-please.outputs.release_tag }} ./dist/mterm_${{ needs.release-please.outputs.major}}.${{ needs.release-please.outputs.minor}}.${{ needs.release-please.outputs.patch}}${{ vars.RELEASE_LABEL }}_amd64.deb

