on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created:  ${{ steps.release.outputs.release_created }}
      release_tag:  ${{ steps.release.outputs.tag_name }}
      major:  ${{ steps.release.outputs.major }}
      minor:  ${{ steps.release.outputs.minor }}
      patch:  ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node

  okay-release-windows:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build
        uses: borales/actions-yarn@v4
        env:
          GH_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        with:
          cmd: build:win

  okay-release-linux:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build
        uses: borales/actions-yarn@v4
        env:
          GH_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        with:
          cmd: build:linux

  okay-release-mac:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build
        uses: borales/actions-yarn@v4
        with:
          cmd: build:mac
        env:
          GH_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CSC }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
